stages:
  data_ingestion:
    cmd: python src/heartDiseaseClassification/pipeline/stage_01_data_ingestion.py
    deps:
      - src/heartDiseaseClassification/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/my_data.csv

  preprocessing_data:
    cmd: python src/heartDiseaseClassification/pipeline/stage_02_data_preprocessing.py
    deps:
      - src/heartDiseaseClassification/pipeline/stage_02_data_preprocessing.py
      - artifacts/data_ingestion
      - config/config.yaml
    outs:
      - artifacts/preprocessing_data
    
  prepare_model:
    cmd: python src/heartDiseaseClassification/pipeline/stage_03_prepare_model.py
    deps:
      - src/heartDiseaseClassification/pipeline/stage_03_prepare_model.py
      - artifacts/preprocessing_data
      - config/config.yaml
    outs:
      - artifacts/prepare_models/voting_clf.pkl
    