artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/AdityaSurve/PyNeuroNet/raw/main/mldata.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

preprocessing_data:
  root_dir: artifacts/preprocessing_data
  data_path: artifacts/data_ingestion/my_data.csv
  result_data_path: artifacts/preprocessing_data

prepare_model:
  root_dir: artifacts/prepare_models
  data_path: artifacts/preprocessing_data
  model_path: artifacts/prepare_models

generate_report:
  root_dir: artifacts/generate_report
  model_path: artifacts/prepare_base_model/base_model_updated.joblib
  report_path: artifacts/generate_report/report.txt